[workspace]
members = [
    "linkall-core",
    "linkall-cli",
    "platforms/linux",
    "platforms/windows/tray",
]
resolver = "2"

[workspace.package]
version = "1.4.0"
edition = "2021"
authors = ["Link All Contributors"]
license = "AGPL-3.0-only"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
panic = "abort"

[profile.bench]
[profile.dev.package.sha2]
opt-level = 3
[profile.dev.package.aes-gcm]
opt-level = 3
[profile.dev.package.x25519-dalek]
opt-level = 3
[profile.dev.package.lz4_flex]
opt-level = 3
