//! Fuzz targets for the Link All protocol and crypto layers.
//!
//! # v3 fix (Fix 4)
//! The `#[cfg(fuzzing)]` block previously referenced `ExtensionFilter` which
//! did not exist in filter.rs, causing compilation failure in fuzz mode.
//! `ExtensionFilter` was added to filter.rs in v2 and `bincode` was added to
//! dev-dependencies in v3 so the integration test stubs compile correctly
//! in normal (non-fuzzing) `cargo test` mode without a separate crate override.
//!
//! Run with libFuzzer:
//!   cargo +nightly fuzz run fuzz_protocol -- -max_len=65536
//!   cargo +nightly fuzz run fuzz_crypto    -- -max_len=1024
//!   cargo +nightly fuzz run fuzz_chunked   -- -max_len=200000
//!
//! Install: cargo install cargo-fuzz
//!
//! Each fuzz target is a standalone binary in fuzz/fuzz_targets/.
//! This file documents the strategy; actual cargo-fuzz targets are in
//! fuzz/fuzz_targets/ (generated by `cargo fuzz init`).
//!
//! # What we fuzz
//!
//! 1. **Protocol deserializer**: Feed arbitrary bytes to `postcard::from_bytes`
//!    for every AppMessage variant. Must not panic.
//!
//! 2. **Crypto decrypt**: Feed arbitrary bytes as "encrypted frames" to
//!    `SessionKey::decrypt`. Must return Err, never panic.
//!
//! 3. **Chunked reassembler**: Feed malformed ChunkMessages in arbitrary order.
//!    Must return Err on invalid sequences, never panic.
//!
//! 4. **Filter chain**: Feed arbitrary `ClipboardContent` bytes.
//!    Must return a Verdict, never panic.
//!
//! 5. **Trust store**: Feed arbitrary JSON to `TrustStore::load`.
//!    Must return Ok or Err gracefully.

#![allow(unexpected_cfgs)]

// ── Fuzz target implementations ───────────────────────────────────────────────
// These are compiled only under `cargo fuzz`, controlled by the feature flag.
// Outside that context, this file serves as documentation and unit stubs.

#[cfg(fuzzing)]
pub mod targets {
    use libfuzzer_sys::fuzz_target;
    use linkall_core::{
        chunked::{ChunkMessage, Reassembler},
        filter::{ExtensionFilter, FilterChain, SizeFilter},
        protocol::AppMessage,
    };

    // ── Fuzz 1: Protocol deserializer ─────────────────────────────────────────

    fuzz_target!(|data: &[u8]| {
        // Must not panic on arbitrary input.
        let _ = postcard::from_bytes::<AppMessage>(data);
    });

    // ── Fuzz 2: Chunked reassembler ───────────────────────────────────────────

    fuzz_target!(|data: &[u8]| {
        let msgs: Vec<ChunkMessage> = match postcard::from_bytes(data) {
            Ok(v) => v,
            Err(_) => return,
        };
        let mut r = Reassembler::default();
        for msg in msgs {
            // Must not panic — may return Ok or Err.
            let _ = r.feed(msg);
        }
    });

    // ── Fuzz 3: Filter chain ──────────────────────────────────────────────────

    fuzz_target!(|data: &[u8]| {
        use linkall_core::protocol::ClipboardContent;
        let content = if data.len() > 0 {
            match data[0] % 3 {
                0 => ClipboardContent::Text(String::from_utf8_lossy(&data[1..]).into_owned()),
                1 => ClipboardContent::Image {
                    mime: "image/png".into(),
                    data: data[1..].to_vec(),
                },
                _ => ClipboardContent::File {
                    name: String::from_utf8_lossy(&data[1..16.min(data.len())]).into_owned(),
                    data: data[1..].to_vec(),
                },
            }
        } else {
            return;
        };

        let mut chain = FilterChain::default();
        chain.push(SizeFilter {
            max_bytes: 64 * 1024 * 1024,
        });
        chain.push(ExtensionFilter::default());
        let _ = chain.run(&content);
    });
}

// ── Unit stubs (always compiled) ──────────────────────────────────────────────

/// Sanity-check the fuzzing strategy with deterministic inputs.
#[cfg(test)]
mod fuzz_sanity {
    use linkall_core::{
        chunked::Reassembler,
        filter::{ExtensionFilter, FilterChain, SizeFilter},
        protocol::{AppMessage, ClipboardContent},
    };

    #[test]
    fn deserialize_garbage_does_not_panic() {
        let garbage = [0xFF_u8; 128];
        let _ = postcard::from_bytes::<AppMessage>(&garbage);
    }

    #[test]
    fn reassembler_rejects_unknown_transfer_id() {
        use linkall_core::chunked::ChunkMessage;
        let mut r = Reassembler::default();
        let unknown_id = [0xDE; 16];
        let result = r.feed(ChunkMessage::Chunk {
            transfer_id: unknown_id,
            index: 0,
            data: vec![0; 64],
        });
        assert!(result.is_err(), "unknown transfer ID must return Err");
    }

    #[test]
    fn filter_chain_handles_empty_content() {
        let mut chain = FilterChain::default();
        chain.push(SizeFilter { max_bytes: 1024 });
        chain.push(ExtensionFilter::default());
        let content = ClipboardContent::Text(String::new());
        // Must not panic.
        let _ = chain.run(&content);
    }

    #[test]
    fn filter_chain_handles_very_long_filename() {
        let mut chain = FilterChain::default();
        chain.push(ExtensionFilter::default());
        let content = ClipboardContent::File {
            name: "a".repeat(65536) + ".pdf",
            data: vec![],
        };
        let _ = chain.run(&content);
    }

    #[test]
    fn deserialize_empty_bytes_does_not_panic() {
        let _ = postcard::from_bytes::<AppMessage>(&[]);
    }

    #[test]
    fn deserialize_truncated_does_not_panic() {
        // Valid start of a bincode-encoded message, then truncated.
        let truncated = [0x00, 0x00, 0x00, 0x00, 0x68];
        let _ = postcard::from_bytes::<AppMessage>(&truncated);
    }
}
